# Generated by Django 3.1 on 2020-10-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('last_degree', models.CharField(max_length=120)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.email')),
            ],
        ),
    ]
